name = "Jupo"
uuid = "8f244b7b-1faa-43f2-9263-7277bb914622"
authors = ["Ush Hamilton"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
